version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.1
     steps:
       - checkout
       - run: pip install awscli
       - run: export PATH=~/.local/bin:$PATH
       - run: aws --version
