version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.1
     steps:
       - checkout
       - run: pip install awscli --upgrade --user
       - run: ls -al /usr/local/bin/python ~/.local/bin
       - run: export PATH=~/.local/bin:$PATH
       - run: aws --version
