version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.1
     steps:
       - checkout
       - run: pip install awscli --upgrade --user
       - run: sudo echo -n "export PATH=~/.local/bin:$PATH" > ~/.bashrc
       - run: ~/.local
