version: 2
jobs:
   build:
     docker:
       image: circleci/python:3.6.1
     branches:
      only:
        - master
     steps:
       - checkout
      run:
        name: cheking dir
        command: ls -a
