version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.1
     steps:
       - checkout
       - run: ls -a
       - run: uname -a
       - run: sudo apt-get install apt-transport-https
       - run:
           name: Register the trusted Microsoft signature key
           command: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
       - run: sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
       - run:
           name: Register the Microsoft Product feed for your distro version
           command: sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
       - run:
           name: Updating package list
           command: sudo apt-get update
       - run:
           name: Installing Dotnet deb
           command: sudo apt-get install dotnet-sdk-2.0.0
       - run:
           name: checking dotnet status
           command: dotnet help
