version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.1
     steps:
       - checkout
       - run: ls -a
       - run:
           name: Adding Dotnet deb package
           command: sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
       - run:
           name: Adding key Dotnet package
           command: sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
       - run:
           name: updating package list
           command: sudo apt-get update
       - run:
           name: Installing Dotnet core and cli
           command: sudo apt-get install dotnet-sdk-2.0.0
       - run:
           name: test
           command: dotnet help
