version: 2
jobs:
   build:
     docker:
       - image: microsoft/dotnet:1.0-sdk
     steps:
       - checkout
       - run: apt-get install python-pip -y
       - run: pip install awscli
       - run: export PATH=~/.local/bin:$PATH
       - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
       - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
       - run: aws configure set region us-east-1
       - run: aws configure set output json
       - run: dotnet --info
       - run: dotnet restore
       - run: dotnet lambda deploy-function LambdaFunCSharp --function-role lambda_basic_execution
