version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.1
     steps:
       - checkout
       - run: sudo pip install awscli
       - run: export PATH=~/.local/bin:$PATH
       - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
       - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
       - run: aws configure set region us-east-1
       - run: aws configure set output json
       - run: sudo apt-get install apt-transport-https
       - run:
           name: Register the Microsoft Product feed for your distro version
           command: sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
       - run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
       - run:
           name: Updating package list
           command: sudo apt-get update
       - run:
           name: Installing Dotnet deb
           command: sudo apt-get install dotnet-sdk-ubuntu-x64.1.0.1
       - run:
           name: Restoring Dotnet
           command: dotnet restore
       - run:
           name: deploying lambda function
           command: dotnet lambda deploy-function LambdaFunCSharp --function-role lambda_basic_execution
